all : prefsGeneral.html prefsHabitat.html prefsSubstrate.html prefsTimezone.html
.PHONY : all

prefsGeneral.html : prefsGeneral.md
	markdown prefsGeneral.md > prefsGeneral.html
	
prefsHabitat.html : prefsHabitat.md
	markdown prefsHabitat.md > prefsHabitat.html
	
prefsSubstrate.html : prefsSubstrate.md
	markdown prefsSubstrate.md > prefsSubstrate.html
	
prefsTimezone.html : prefsTimezone.md
	markdown prefsTimezone.md > prefsTimezone.html
